FROM debian:jessie

RUN apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E && \
    echo "deb http://deb.debian.org/debian/ jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list && \
    echo "deb http://packages.x2go.org/debian jessie main" > /etc/apt/sources.list.d/x2go.list && \
    apt-get update && apt-get install -y -q openssh-server gosu && \
    echo X11UseLocalhost no >> /etc/ssh/sshd_config

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q x2go-keyring x2goserver=4.1.0.0-0x2go1.2+git20180302.1517+8.main.1 x2goclient=4.1.1.1-0x2go1+git20180302.1732+8.main.1

RUN apt-get update && apt-get install -y -q python3-pip && \
    pip3 install namedlist

RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN mkdir -p /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix

ENV GUEST_USER=user \
    GUEST_UID=9001 \
    GUEST_GROUP=user \
    GUEST_GID=9001 \
    X2GO_DPI=72 \
    DISPLAY=:1

ADD common/ debian-series/ /docker/
RUN chmod a+x /docker/*
EXPOSE 22
ENTRYPOINT ["/docker/entrypoint.sh"]
