FROM debian:stretch

RUN apt-get update && apt-get install -y -q openssh-server gosu gnupg2 && \
    echo X11UseLocalhost no >> /etc/ssh/sshd_config

RUN echo "deb http://packages.x2go.org/debian stretch main" > /etc/apt/sources.list.d/x2go.list && \
    apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q x2go-keyring x2goserver=4.1.0.3-0x2go1+git20191115.1708+9.main.1 x2goclient=4.1.2.2-0x2go1+git20200213.1926+9.main.1

RUN apt-get update && apt-get install -y -q python3-pip && \
    pip3 install namedlist

RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN mkdir -p /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix

ENV GUEST_USER=user \
    GUEST_UID=9001 \
    GUEST_GROUP=user \
    GUEST_GID=9001 \
    X2GO_DPI=72 \
    DISPLAY=:1

ADD common/ debian-series/ /docker/
RUN chmod a+x /docker/*
EXPOSE 22
ENTRYPOINT ["/docker/entrypoint.sh"]
