FROM debian:jessie

RUN apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E && \
    echo "deb http://deb.debian.org/debian/ jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list && \
    echo "deb http://packages.x2go.org/debian jessie main" > /etc/apt/sources.list.d/x2go.list && \
    apt-get update && \
    apt-get install -q -y x2go-keyring && \
    apt-get install -q -y openssh-server gosu x2goserver=4.0.1.20-0x2go1+git20170412.1125+8.main.1 x2goclient=4.1.0.0-0x2go1+git20170413.1549+8.main.1

RUN apt-get update && \
    apt-get install -q -y python3-pip && \
    pip3 install namedlist

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

RUN mkdir -p /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix

ENV GUEST_USER=user \
    GUEST_UID=9001 \
    GUEST_GROUP=user \
    GUEST_GID=9001 \
    X2GO_DPI=72 \
    DISPLAY=:1

ADD common/ debian-series/ /docker/
RUN chmod a+x /docker/*
EXPOSE 22
ENTRYPOINT ["/docker/entrypoint.sh"]
