FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -q -y software-properties-common && \
    add-apt-repository ppa:x2go/stable && \
    apt-get update && \
    apt-get install -q -y openssh-server gosu x2goserver=4.0.1.20-0~1125~ubuntu16.04.1 x2goclient=4.1.0.0-0~1536~ubuntu16.04.1

RUN apt-get update && \
    apt-get install -q -y python3-pip && \
    pip3 install namedlist

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

RUN mkdir -p /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix

ENV GUEST_USER=user \
    GUEST_UID=9001 \
    GUEST_GROUP=user \
    GUEST_GID=9001 \
    X2GO_DPI=72 \
    DISPLAY=:1

ADD common/ debian-series/ /docker/
RUN chmod a+x /docker/*
EXPOSE 22
ENTRYPOINT ["/docker/entrypoint.sh"]
